### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by RobertPlant** [rupansh/passmenu-rs#2]
It would be great if you publish this project to crates.io

I would also like it in the AUR too but if you don't use arch I can submit it to the AUR pointing at the crates.io archive.

**Comment by rupansh** [comment]
published on AUR.

crates.io is blocked by https://github.com/rupansh/passmenu-rs/blob/master/Cargo.toml#L11
I am hesitant to push the rustofi fork on crates.io.

**Comment by RobertPlant** [comment]
Perfect, thanks for publishing it :)
